### ISSUE TITLE
Help_wanted

### ISSUE THREAD

**Issue by ronygolderku** [dgumustel/blog_visualizations#1]
Hello,
Firstly, I want to thank you for MODIS data visualization. I applied this code for our region successfully. But I want to add basemap and a particular multi polygon shapefile to my map. Could you please, help me to develop the code.

Thanks once again.

Kind regards,
Rony

**Comment by dgumustel** [comment]
Hi there,
Thanks for the request! I'll be happy to try putting together a basemap and shapefile example this week.

**Comment by dgumustel** [comment]
Resolved this offline, closing issue.
