### ISSUE TITLE
want datasets

### ISSUE THREAD

**Issue by qazwsxpy** [dgumustel/blog_visualizations#2]
hi, i do you have a copy of scow_monthly_maps.nc ?
i found it 404 now

**Comment by dgumustel** [comment]
Sorry, which dataset are you referring to?

**Comment by qazwsxpy** [comment]
in

> blog_visualizations/ekman-transport/ekman.ipynb

the second cell
`scow = xr.open_dataset('http://wilson.coas.oregonstate.edu:8080/thredds/dodsC/CIOSS/SCOW/Monthly/scow_monthly_maps.nc')
`
but i found it in 'http://nanoos.ceoas.oregonstate.edu/thredds/dodsC/CIOSS/SCOW/Monthly/scow_monthly_maps.nc'

thank you

**Comment by dgumustel** [comment]
Glad you were able to find it! Closing the issue.
